### ISSUE TITLE
Plugin causes opening web-page

### ISSUE THREAD

**Issue by Sgt1503** [Lich-Corals/Nautilus-fileconverter-43#19]
**Describe the bug**
Plugin causes opening web-page of release notes since version 1.20. I'm using ubuntu 23.10. I reopen nautilus >20 per day and every reopening causes opening release notes page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start process of nautilus.

**Expected behaviour**
Nothing.

**OS**
 - OS Name:  Ubuntu 23.10
 - Package manager: apt, snap
 - Gnome version: GNOME 45.2
 - Nautilus version (`nautilus --version`): GNOME nautilus 45.rc
 - Python version (`python3 --version`): Python 3.11.6
 - pip version (`pip --version`):  23.2
 
**Nautilus errors**
WARNING(Nautilus-file-converter): "pyheif" not found, if you want to convert from heif format, install the package using "pip install pyheif". See the readme on GitHub for more information.
WARNING(Nautilus-file-converter): "jxlpy" not found, if you want to convert from- or to jxl format, install the package using "pip install jxlpy". See the readme on GitHub for more information.

**Comment by Sgt1503** [comment]
In addition: It opens every time when I login to pc after sleep.

**Comment by Lich-Corals** [comment]
Thank you for reporting!
Based on the errors, it looks like the script in's the latest version and installed in the root installation folder.
Please check, where the installation is placed and which version is installed (unique version number can be found in one of the first lines of the script).

**Comment by Lich-Corals** [comment]
I just pushed an update, the page shouldn't open any more. 
If the script is installed in the root location, I'd still recommend moving it to the home installation location or giving the script permissions to edit itself and the config file. More information about this is in [here](https://github.com/Lich-Corals/Nautilus-fileconverter-43/blob/main/README.md#002-no-permission-to-self-update) and [here](https://github.com/Lich-Corals/Nautilus-fileconverter-43/blob/main/README.md#003-no-permission-to-write-configuration-file).

I hope this is helpful for you, please let me know or close the issue if your problem is solved.

**Comment by Sgt1503** [comment]
It worked, thank you for extension and your help!
